### ISSUE TITLE
每次运行脚本都会重复安装SteamCMD的过程，能否增加选项，直接进入最后的控制界面

### ISSUE THREAD

**Issue by xuxianhe** [g-glory-n/DST_server_deploy#1]
脚本非常棒，但是用的时候发现:
1，想打开控制菜单时，总是要重复全部安装过程才能进入最后的控制界面；
2，最后显示运行信息似乎有bug，不能调用screen显示进程；
能否改进，谢谢

**Comment by g-glory-n** [comment]
第一次运行是安装依赖环境，依赖环境安装完成再运行就是管理界面，至于 screen bug 可以截图发到邮箱（g-glory-n@g-glory-n.top），脚本的开发测试环境是 Debian 8，其他环境未进行完整测试，可能会有 bug。

**Comment by xuxianhe** [comment]
第一次运行我肯定理解的
我的意思是说安装之后，再运行还是会执行SteamCMD等其他东西的安装，其实应该是全都执行了一边
只有游戏因为是最新的才没有更新,估计是判断部分有bug
我的使用环境是ubuntu18.04

我提个建议：在启动脚本最开始加个菜单，人为选择执行安装、更新、还是直接进入最后的管理菜单，这样也不用去测什么bug了    ;-p

> 第一次运行是安装依赖环境，依赖环境安装完成再运行就是管理界面，至于 screen bug 可以截图发到邮箱（[g-glory-n@g-glory-n.top](mailto:g-glory-n@g-glory-n.top)），脚本的开发测试环境是 Debian 8，其他环境未进行完整测试，可能会有 bug。

**Comment by xuxianhe** [comment]
多谢回复，建议我写在issue里了😋

g-glory-n ***@***.***> 于2021年7月18日周日 下午9:53写道：

**Comment by g-glory-n** [comment]
> 
> 
> 脚本非常棒，但是用的时候发现:
> 1，想打开控制菜单时，总是要重复全部安装过程才能进入最后的控制界面；
> 2，最后显示运行信息似乎有bug，不能调用screen显示进程；
> 能否改进，谢谢

**Comment by g-glory-n** [comment]
> 
> 
> 第一次运行我肯定理解的
> 我的意思是说安装之后，再运行还是会执行SteamCMD等其他东西的安装，其实应该是全都执行了一边
> 只有游戏因为是最新的才没有更新,估计是判断部分有bug
> 我的使用环境是ubuntu18.04
> 
> 我提个建议：在启动脚本最开始加个菜单，人为选择执行安装、更新、还是直接进入最后的管理菜单，这样也不用去测什么bug了 ;-p
> 
> > 第一次运行是安装依赖环境，依赖环境安装完成再运行就是管理界面，至于 screen bug 可以截图发到邮箱（[g-glory-n@g-glory-n.top](mailto:g-glory-n@g-glory-n.top)），脚本的开发测试环境是 Debian 8，其他环境未进行完整测试，可能会有 bug。

使用 loop 替代下面这几行，即可运行直接进入管理界面，前提是依赖环境安装完成了。
```
welcome
install_judge
if [ "$has_install" = "yes" ]
then
    loop
else
    init_loop
fi
```

**Comment by xuxianhe** [comment]
> > 第一次运行我肯定理解的
> > 我的意思是说安装之后，再运行还是会执行SteamCMD等其他东西的安装，其实应该是全都执行了一边
> > 只有游戏因为是最新的才没有更新,估计是判断部分有bug
> > 我的使用环境是ubuntu18.04
> > 我提个建议：在启动脚本最开始加个菜单，人为选择执行安装、更新、还是直接进入最后的管理菜单，这样也不用去测什么bug了 ;-p
> > > 第一次运行是安装依赖环境，依赖环境安装完成再运行就是管理界面，至于 screen bug 可以截图发到邮箱（[g-glory-n@g-glory-n.top](mailto:g-glory-n@g-glory-n.top)），脚本的开发测试环境是 Debian 8，其他环境未进行完整测试，可能会有 bug。
> 
> 使用 loop 替代下面这几行，即可运行直接进入管理界面，前提是依赖环境安装完成了。
> 
> ```
> welcome
> install_judge
> if [ "$has_install" = "yes" ]
> then
>     loop
> else
>     init_loop
> fi
> ```

暂时解决了，谢谢作者
